# Generated by Django 4.0.6 on 2022-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidadelitros', models.PositiveSmallIntegerField()),
                ('km_odometro', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bombas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocombustivel', models.CharField(max_length=100)),
                ('quantidadedeestoque', models.PositiveSmallIntegerField()),
                ('capacidadebomba', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompraCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidadelitros', models.PositiveSmallIntegerField()),
                ('precolitro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('capacidadetanque', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
