# Generated by Django 4.0.6 on 2022-10-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocombustivel', models.CharField(max_length=100)),
                ('quantidadedeestoque', models.PositiveSmallIntegerField()),
                ('capacidadebomba', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Abastecimentos',
            new_name='Abastecimento',
        ),
        migrations.RenameModel(
            old_name='Veiculos',
            new_name='Veiculo',
        ),
        migrations.DeleteModel(
            name='Bombas',
        ),
    ]
