# Generated by Django 4.0.6 on 2022-11-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abastecimento', '0004_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
