# Generated by Django 4.0.6 on 2022-11-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abastecimento', '0005_alter_veiculo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ManyToManyField(to='Abastecimento.veiculo'),
        ),
    ]
