# Generated by Django 4.0.6 on 2022-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abastecimento', '0006_abastecimento_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracombustivel',
            name='bomba',
            field=models.ManyToManyField(to='Abastecimento.bomba'),
        ),
    ]
